name: Secure hadolint
description: |
  This action securely runs hadolint in a Docker container to lint Dockerfiles.
  It reduces security risks from compromised or malicious third-party tools (e.g., compromised repositories or tampered container images).
  To achieve this, it enforces strict container isolation, disables network connections, and drops unnecessary privileges.

  ## Usage

  ```yaml
    steps:
      - name: Secure hadolint
        uses: tmknom/secure-hadolint-action@v0
  ```

runs:
  using: composite

  steps:
    - name: Install
      id: install
      run: |
        echo "::group::Install"
        set -x
        image="hadolint/hadolint"
        echo "image=${image}" >> "${GITHUB_OUTPUT}"
        docker pull "${image}"
      shell: bash

    - name: Show version
      env:
        IMAGE: ${{ steps.install.outputs.image }}
      run: |
        echo "::group::Show version"
        set -x
        docker run --interactive --rm --read-only --user 1111:1111 \
          --security-opt no-new-privileges --cap-drop all --network none \
          "${IMAGE}" hadolint --version
        echo "::endgroup::"
      shell: bash

    - name: Run
      env:
        IMAGE: ${{ steps.install.outputs.image }}
      run: |
        echo "::group::Run"
        set -x
        docker run --interactive --rm --read-only --user 1111:1111 \
          --security-opt no-new-privileges --cap-drop all --network none \
          --volume "${PWD}:${PWD}:ro" --workdir "${PWD}" \
          "${IMAGE}" hadolint $(find . -name 'Dockerfile')
        echo "::endgroup::"
      shell: bash
