name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Setup
        run: |
          set -x
          cat <<EOF > ".github/Dockerfile"
          FROM scratch
          EOF

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true

      - name: Verify
        env:
          OUTCOME: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${OUTCOME}" = "success"

  test-error:
    name: Test error
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Setup
        run: |
          set -x
          cat <<EOF > ".github/Dockerfile"
          USER invalid
          EOF

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true

      - name: Verify
        env:
          OUTCOME: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${OUTCOME}" = "failure"

  test-ignore:
    name: Test ignore
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Setup
        run: |
          set -x
          cat <<EOF > "./Dockerfile"
          USER invalid
          COPY README.md README.md
          EOF

      - name: Exercise
        id: exercise
        uses: ./
        with:
          ignore: DL3061 DL3045

      - name: Verify
        env:
          OUTCOME: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${OUTCOME}" = "success"
